/*
    create table tb_clientes (
       cliente_id integer generated by default as identity,
        cpf varchar(255) not null,
        email varchar(255) not null,
        idade integer not null check (idade<=90 AND idade>=18),
        nome varchar(255) not null,
        renda_mensal decimal(19,2) not null check (renda_mensal>=0),
        regime_contratacao varchar(255) not null,
        primary key (cliente_id)
    )
Hibernate: 
    
    create table tb_conta (
       id_conta integer generated by default as identity,
        agencia varchar(255),
        limite_disponivel decimal(19,2),
        numero_conta varchar(255),
        cliente_id integer,
        primary key (id_conta)
    )
Hibernate: 
    
    create table tb_enderecos (
       endereco_id integer generated by default as identity,
        bairro varchar(255) not null,
        cep varchar(255) not null,
        cidade varchar(255) not null,
        complemento varchar(255),
        estado varchar(255) not null,
        logradouro varchar(255) not null,
        numero varchar(255) not null,
        cliente_id integer,
        primary key (endereco_id)
    )
Hibernate: 
    
    create table tb_telefones (
       id integer generated by default as identity,
        telefones varchar(255) not null,
        cliente_cliente_id integer,
        primary key (id)
    )
Hibernate: 
    
    create table tb_transacoes (
       id integer generated by default as identity,
        agencia varchar(255),
        banco varchar(255),
        data_hora_operacao timestamp,
        nome_depositante varchar(255),
        nome_destinatario varchar(255),
        numero_conta_destino varchar(255),
        numero_conta_origem varchar(255),
        operacao varchar(255) not null,
        valor decimal(19,2) not null,
        primary key (id)
    )
Hibernate: 
    
    alter table tb_clientes 
       add constraint UK_rl87ok1y442c0jopurhg1lodw unique (cpf)
Hibernate: 
    
    alter table tb_clientes 
       add constraint UK_9o6dwdqix5udt21xn0tsq4m7m unique (email)
Hibernate: 
    
    alter table tb_conta 
       add constraint FKot08ftx4iu6pbghwwqycxsj0y 
       foreign key (cliente_id) 
       references tb_clientes
Hibernate: 
    
    alter table tb_enderecos 
       add constraint FKtjgooj5176dkbo5n6qv493jxh 
       foreign key (cliente_id) 
       references tb_clientes
Hibernate: 
    
    alter table tb_telefones 
       add constraint FKm9nrfv413aik045g2f2dwq1oo 
       foreign key (cliente_cliente_id) 
       references tb_clientes      
*/

INSERT INTO tb_clientes (cpf, email, idade, nome, regime_contratacao, renda_mensal) VALUES ('999.999.999-99', 'jose@gmail.com', 38, 'José Santos', 'ASSISTENCIAL', 0.00);
INSERT INTO tb_clientes (cpf, email, idade, nome, regime_contratacao, renda_mensal) VALUES ('111.111.111-11', 'maria@gmail.com', 36, 'Maria Alves', 'FORMAL', 10000.00);

INSERT INTO tb_telefones (cliente_cliente_id, telefones) VALUES (1, '(11) 98058-6008');
INSERT INTO tb_telefones (cliente_cliente_id, telefones) VALUES (1, '(11) 96972-4155');
INSERT INTO tb_telefones (cliente_cliente_id, telefones) VALUES (2, '(11) 99999-9999');


INSERT INTO tb_enderecos (bairro, cep, complemento, logradouro, numero, cliente_id, estado, cidade) VALUES ('Jardim das Maravilhas', '09251010', 'Apartamento 1', 'Rua Algeciras', '530', 1, 'SP', 'Santo André');
INSERT INTO tb_enderecos (bairro, cep, complemento, logradouro, numero, cliente_id, estado, cidade) VALUES ('Vila Industrial', '03254240', 'Casa Frente', 'Rua Água Bonita', '230', 2, 'SP', 'São Paulo');

INSERT INTO tb_conta (agencia, limite_disponivel, cliente_id, numero_conta) VALUES ('0001', 600.00, 1, '93693-5');
INSERT INTO tb_conta (agencia, limite_disponivel, cliente_id, numero_conta) VALUES ('0001', 8000.00, 2, '71006-5');
